# Generated by Django 5.2.4 on 2025-07-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('data_arquivamento', models.DateField()),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('estante', models.IntegerField()),
                ('andar', models.IntegerField()),
                ('posicao', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('documentos', models.ManyToManyField(blank=True, related_name='caixas', to='arquivo.documento')),
            ],
        ),
    ]
